const {useEffect,useMemo,useRef,useState}=React;
const KB=8.617e-5,T0=298.15,MAXT=600,A=100;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const damage=(c,t)=>clamp(1-Math.exp(-.0032*(c.pressure/50)*c.attack*t),0,.98);
function model(kind,c,t,bias=true,vOverride=null,tempOverride=null){
  const V=vOverride??c.voltage,Tc=tempOverride??c.temp,D=damage(c,t),d=c.thickness;
  let w,r25,Ea,g,E0,m,trap;
  if(kind==='A'){w=.025+.05*D;r25=1.2e14*10**(-.35*D);Ea=.64-.03*D;g=.08+.05*D;E0=18.5*(1-.18*D);m=10;trap=.05+.07*D}
  else{w=clamp(.07+.18*c.na/15+.25*c.secondary/12+.23*c.gb/100+.58*D,.07,.98);r25=4e13*10**(-2.8*w);Ea=clamp(.59-.18*w,.34,.59);g=.14+.95*w;E0=clamp(15.5*(1-.68*w)*(1-.18*D),3.2,15.5);m=clamp(8.5-5.2*w,3,8.5);trap=clamp(.1+.58*w,.1,.72)}
  const tau=35*10**(2.25*trap),q=(1-trap)*Math.exp(-t/20)+trap*Math.exp(-t/tau),Ve=bias?V:V*q,E=Ve/Math.max(d,.1)/1000,T=Tc+273.15;
  const rhoT=r25*Math.exp(Ea/KB*(1/T-1/T0)),rho=Math.max(rhoT*Math.exp(-g*Math.sqrt(Math.max(E,0))),1e3),R=rho*(d/10)/A,I=Ve>0?Ve/R:0,n=1+.5*g*Math.sqrt(Math.max(E,0));
  const risk=clamp(1-Math.exp(-((Math.max(E,0)/E0)**m)*((Math.max(t,.2)/300)**.62)),0,.9999);
  return{kind,D,w,E,rho,I,n,E0,risk,q,Vres:V*q,P:I*Ve,trap};
}
const amps=x=>x>=1?`${x.toFixed(2)} A`:x>=1e-3?`${(x*1e3).toFixed(2)} mA`:x>=1e-6?`${(x*1e6).toFixed(2)} µA`:x>=1e-9?`${(x*1e9).toFixed(2)} nA`:`${(x*1e12).toFixed(2)} pA`;
function CeramicElectricalReliabilitySimulator(){
 const [c,setC]=useState({voltage:2500,temp:200,thickness:1,pressure:70,attack:1,na:10,secondary:6,gb:65}),[time,setTime]=useState(0),[run,setRun]=useState(false),[bias,setBias]=useState(true),[plot,setPlot]=useState('iv');
 const main=useRef(),graph=useRef(),state=useRef(),tref=useRef(0);state.current={c,time,run,bias,plot};tref.current=time;
 const a=useMemo(()=>model('A',c,time,bias),[c,time,bias]),b=useMemo(()=>model('B',c,time,bias),[c,time,bias]);
 const set=(k,v)=>setC(s=>({...s,[k]:+v})),reset=()=>{setRun(false);setTime(0);tref.current=0;setBias(true)};
 useEffect(()=>{let id,last=performance.now(),lastUI=0;
  const fit=(cv,h1,h2)=>{if(!cv)return;const w=Math.max(280,cv.parentElement.clientWidth),h=w<560?h1:h2,d=Math.min(devicePixelRatio||1,2);if(cv.width!==w*d||cv.height!==h*d){cv.width=w*d;cv.height=h*d;cv.style.width=w+'px';cv.style.height=h+'px'}const x=cv.getContext('2d');x.setTransform(d,0,0,d,0,0);return{x,w,h}};
  const rr=(x,X,Y,W,H,r,f,s)=>{x.beginPath();x.roundRect(X,Y,W,H,r);if(f){x.fillStyle=f;x.fill()}if(s){x.strokeStyle=s;x.stroke()}};
  const arrow=(x,X,Y,L,col)=>{x.strokeStyle=x.fillStyle=col;x.lineWidth=1.5;x.beginPath();x.moveTo(X,Y);x.lineTo(X,Y+L);x.stroke();x.beginPath();x.moveTo(X,Y+L);x.lineTo(X-4,Y+L-7);x.lineTo(X+4,Y+L-7);x.fill()};
  const panel=(x,p,M,weak,S)=>{rr(x,p.x,p.y,p.w,p.h,14,'#0b1624',weak?'#ffb85c':'#39d98a');x.fillStyle='#eef6ff';x.font=`700 ${p.w<210?10:12}px sans-serif`;x.textAlign='center';x.fillText(weak?'CASE B · WEAK GB':'CASE A · CLEAN AlN',p.x+p.w/2,p.y+18);const py=p.y+27,wy=p.y+85,cy=wy+22,ch=p.h-150;
   x.fillStyle='#153245';x.fillRect(p.x+7,py,p.w-14,50);for(let i=0;i<Math.round(4+S.c.pressure/9);i++){const q=(S.time*(.018+.006*S.c.attack)+i*.137)%1;x.fillStyle='#4eebc2';x.beginPath();x.arc(p.x+12+(i*37%91)/91*(p.w-24),py+4+q*42,2,0,7);x.fill()}
   rr(x,p.x+9,wy,p.w-18,13,4,S.bias?'#e5edf6':'#8693a3');x.fillStyle=S.bias?'#ff6b6b':'#aab4bf';x.font='9px sans-serif';x.fillText(S.bias?'+ wafer electrode':'voltage removed',p.x+p.w/2,wy+10);
   const cols=weak?4:5,rows=5,cw=(p.w-22)/cols,rh=ch/rows;for(let r=0;r<rows;r++)for(let q=0;q<cols;q++)rr(x,p.x+11+q*cw+2,cy+r*rh+2,cw-4,rh-4,7,weak?'#303a4c':'#263b49',weak?'#a96f3e':'#28795e');
   if(weak){x.strokeStyle=`rgba(255,184,92,${.4+.5*M.w})`;x.lineWidth=2+5*M.w;x.beginPath();x.moveTo(p.x+p.w*.56,cy);for(let i=1;i<7;i++)x.lineTo(p.x+p.w*(.56+(i%2?.1:-.08)),cy+ch*i/6);x.stroke();for(let i=0;i<Math.round(3+S.c.secondary*.7);i++){x.fillStyle='#d283ff';x.beginPath();x.arc(p.x+12+(i*31%89)/89*(p.w-24),cy+8+(i*53%91)/91*(ch-16),3,0,7);x.fill()}}
   for(let i=0;i<(p.w<210?3:4);i++)arrow(x,p.x+18+(i+.5)*(p.w-36)/(p.w<210?3:4),cy+10,ch-20,`rgba(255,107,107,${clamp(.2+M.E/5,.2,.9)})`);
   const ne=Math.round(clamp(4+Math.log10(1+M.I*1e12)*2,4,22));for(let i=0;i<ne;i++){const q=S.bias?(S.time*(.15+.04*M.E)+i/ne)%1:M.q,Y=cy+ch*(1-q),X=weak?p.x+p.w*(.56+.1*Math.sin(Y/18+i)):p.x+14+(i*41%91)/91*(p.w-28);x.fillStyle='#83ddff';x.beginPath();x.arc(X,Y,2,0,7);x.fill()}
   if(weak)for(let i=0;i<Math.round(S.c.na/2.2);i++){const q=(S.time*.018*(.5+M.E)+i/7)%1,Y=cy+q*ch,X=p.x+p.w*(.56+.1*Math.sin(Y/21+i));x.fillStyle='#ffc66d';x.beginPath();x.arc(X,Y,2.5,0,7);x.fill()}
   if(weak&&M.P>0){const X=p.x+p.w*.56,Y=cy+ch*.57,G=x.createRadialGradient(X,Y,2,X,Y,36);G.addColorStop(0,`rgba(255,70,70,${clamp(Math.log10(1+M.P*1e5)/8,0,.55)})`);G.addColorStop(1,'transparent');x.fillStyle=G;x.beginPath();x.arc(X,Y,36,0,7);x.fill()}
   if(M.risk>.72){x.strokeStyle='#ff4d5a';x.lineWidth=3;x.beginPath();x.moveTo(p.x+p.w*.52,cy);for(let i=1;i<7;i++)x.lineTo(p.x+p.w*(.52+(i%2?.12:-.08)),cy+ch*i/6);x.stroke()}
   rr(x,p.x+13,cy+ch+9,p.w-26,11,4,'#6a7e96');x.fillStyle='#aebed0';x.font='9px sans-serif';x.fillText(`E=${M.E.toFixed(2)} kV/mm`,p.x+p.w/2,p.y+p.h-8)};
  const drawMain=S=>{const f=fit(main.current,455,420);if(!f)return;const{x,w,h}=f;x.fillStyle='#06101c';x.fillRect(0,0,w,h);const pad=7,gap=7,pw=(w-2*pad-gap)/2;panel(x,{x:pad,y:8,w:pw,h:h-40},model('A',S.c,S.time,S.bias),false,S);panel(x,{x:pad+pw+gap,y:8,w:pw,h:h-40},model('B',S.c,S.time,S.bias),true,S);x.font='9px sans-serif';x.textAlign='left';[['#83ddff','electron'],['#ffc66d','Na⁺'],['#4eebc2','F radical'],['#d283ff','trap/phase']].forEach((z,i)=>{x.fillStyle=z[0];x.beginPath();x.arc(10+i*w/4,h-10,3,0,7);x.fill();x.fillStyle='#9fb1c6';x.fillText(z[1],16+i*w/4,h-7)})};
  const drawGraph=S=>{const f=fit(graph.current,305,325);if(!f)return;const{x,w,h}=f;x.fillStyle='#06101c';x.fillRect(0,0,w,h);const L=50,R=12,T=35,B=36,pw=w-L-R,ph=h-T-B;x.strokeStyle='#39516c';x.strokeRect(L,T,pw,ph);let title,xmax=5000,ymin=-12,ymax=0,log=true,curves=[],pointX=S.c.voltage;
   if(S.plot==='iv'){title='Leakage current vs voltage';const xs=Array.from({length:70},(_,i)=>1+i*4999/69);curves=[['#39d98a',xs.map(v=>[v,Math.log10(Math.max(model('A',S.c,S.time,true,v).I,1e-12))])],['#ff6675',xs.map(v=>[v,Math.log10(Math.max(model('B',S.c,S.time,true,v).I,1e-12))])]]}
   else if(S.plot==='rho'){title='Resistivity vs temperature';xmax=600;ymin=5;ymax=15;pointX=S.c.temp;const xs=Array.from({length:70},(_,i)=>25+i*575/69);curves=[['#39d98a',xs.map(v=>[v,Math.log10(model('A',S.c,S.time,true,null,v).rho)])],['#ff6675',xs.map(v=>[v,Math.log10(model('B',S.c,S.time,true,null,v).rho)])]]}
   else if(S.plot==='risk'){title='Breakdown risk vs time';xmax=600;ymin=0;ymax=1;log=false;pointX=S.time;const xs=Array.from({length:70},(_,i)=>i*600/69);curves=[['#39d98a',xs.map(v=>[v,model('A',S.c,v,true).risk])],['#ff6675',xs.map(v=>[v,model('B',S.c,v,true).risk])]]}
   else{title='Residual voltage after bias off';xmax=600;ymin=0;ymax=S.c.voltage;log=false;pointX=S.time;const xs=Array.from({length:70},(_,i)=>i*600/69);curves=[['#39d98a',xs.map(v=>[v,model('A',S.c,v,false).Vres])],['#ff6675',xs.map(v=>[v,model('B',S.c,v,false).Vres])]]}
   x.fillStyle='#eef6ff';x.font='700 12px sans-serif';x.fillText(title,L,T-13);for(let i=0;i<6;i++){const X=L+pw*i/5,Y=T+ph*i/5;x.strokeStyle='#20364c';x.beginPath();x.moveTo(X,T);x.lineTo(X,T+ph);x.stroke();x.beginPath();x.moveTo(L,Y);x.lineTo(L+pw,Y);x.stroke()}const mx=v=>L+v/xmax*pw,my=v=>T+ph*(1-(v-ymin)/(ymax-ymin));curves.forEach(z=>{x.strokeStyle=z[0];x.lineWidth=2;x.beginPath();z[1].forEach((q,i)=>i?x.lineTo(mx(q[0]),my(q[1])):x.moveTo(mx(q[0]),my(q[1])));x.stroke()});x.fillStyle='#9fb1c6';x.font='9px sans-serif';x.fillText('Case A',L+5,T+12);x.fillStyle='#39d98a';x.fillRect(L+42,T+6,15,2);x.fillStyle='#9fb1c6';x.fillText('Case B',L+68,T+12);x.fillStyle='#ff6675';x.fillRect(L+105,T+6,15,2);x.fillStyle='#aebed0';x.textAlign='center';x.fillText(S.plot==='rho'?'Temperature (°C)':S.plot==='iv'?'Voltage (V)':'Time (s)',L+pw/2,h-9)};
  const tick=now=>{const S=state.current,dt=Math.min((now-last)/1000,.1);last=now;if(S.run){const n=clamp(tref.current+dt*12,0,MAXT);tref.current=n;S.time=n;if(now-lastUI>55||n===MAXT){setTime(n);lastUI=now}if(n===MAXT)setRun(false)}drawMain(S);drawGraph(S);id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[]);
 const defs=[['voltage','Voltage',0,5000,50,'V'],['temp','Temperature',25,600,5,'°C'],['thickness','Thickness',.5,3,.05,'mm'],['pressure','F pressure',0,100,2,'mTorr'],['attack','F attack rate',0,2,.05,'×'],['na','Sodium',0,15,.5,'ppm'],['secondary','Secondary phase',0,12,.5,'vol%'],['gb','GB connectivity',0,100,2,'%']];
 const card=(name,M,col)=><section className="case" style={{borderColor:col}}><h3 style={{color:col}}>{name}</h3><div className="stats">{[['Field',M.E.toFixed(2)+' kV/mm'],['Resistivity',M.rho.toExponential(2)+' Ω·cm'],['Leakage',amps(M.I)],['I–V n',M.n.toFixed(2)],['Breakdown E₀',M.E0.toFixed(2)+' kV/mm'],['Risk',(100*M.risk).toFixed(2)+'%'],['Residual V',Math.round(M.Vres)+' V'],['Power',M.P<.001?(M.P*1e3).toFixed(2)+' mW':M.P.toFixed(2)+' W'],['Weakness',M.w.toFixed(3)],['F damage',M.D.toFixed(3)]].map(z=><div><span>{z[0]}</span><b>{z[1]}</b></div>)}</div></section>;
 return <main data-testid="root" data-model={`${a.E}|${a.rho}|${b.w}|${b.D}|${b.I}|${b.risk}`} className="page"><style>{`*{box-sizing:border-box}html,body,#root{margin:0;width:100%;min-height:100%;overflow-x:hidden;background:#050b13;color:#edf6ff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.page{max-width:1080px;margin:auto;padding:12px}.card,.case{background:#091421;border:1px solid #243a52;border-radius:15px;padding:10px;margin:10px 0}h1{font-size:clamp(24px,6vw,40px);margin:4px 0 6px;line-height:1.08}.sub{color:#a9bacd;font-size:13px;line-height:1.45}.buttons{display:flex;flex-wrap:wrap;gap:6px;align-items:center}button,select{min-height:44px;border:1px solid #35516d;border-radius:10px;background:#122338;color:#fff;padding:7px 11px;font-weight:700;touch-action:manipulation}.go{background:#39d98a;color:#07130e}.on{background:#ffb85c;color:#1b1003}.time{display:grid;grid-template-columns:32px 1fr 45px;gap:7px;align-items:center;font-size:11px}input[type=range]{width:100%;accent-color:#39d98a;touch-action:pan-y}canvas{display:block;max-width:100%;border-radius:10px}.controls{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}.ctrl{background:#0e1e30;border-radius:10px;padding:8px;font-size:11px}.ctrl label{display:flex;justify-content:space-between;gap:5px}.cases{display:grid;grid-template-columns:1fr 1fr;gap:9px}.case h3{font-size:14px;margin:0 0 7px}.stats{display:grid;grid-template-columns:1fr 1fr;gap:6px}.stats div{background:#0e1e30;border-radius:8px;padding:7px}.stats span{display:block;color:#91a5bc;font-size:9px}.stats b{font-size:11px;overflow-wrap:anywhere}.plothead{display:flex;justify-content:space-between;align-items:center}.eq{display:grid;grid-template-columns:1fr 1fr;gap:8px}.eq div{background:#0e1e30;border-radius:10px;padding:9px}.eq p{font-size:11px;color:#a9bacd;line-height:1.45;margin:5px 0}.mono{font-family:ui-monospace,monospace;color:#fff!important}@media(max-width:560px){.page{padding:8px}.cases,.eq{grid-template-columns:1fr}.controls{grid-template-columns:1fr 1fr}.ctrl label{display:block}.ctrl b{display:block;margin-top:2px}button,select{font-size:12px;padding:6px 8px}}`}</style>
 <h1>AlN Ceramic Electrical Reliability Simulator</h1><p className="sub">Dense clean AlN versus a weak, connected grain-boundary network. Watch electrons, Na⁺ ions, fluorine attack, local heating, breakdown risk, and charge decay respond together.</p>
 <section className="card"><div className="buttons"><button className="go" data-testid="play" onClick={()=>setRun(true)}>▶ Play</button><button data-testid="pause" onClick={()=>setRun(false)}>Ⅱ Pause</button><button data-testid="reset" onClick={reset}>↺ Reset</button><button data-testid="bias" className={bias?'on':''} onClick={()=>setBias(x=>!x)}>{bias?'Bias ON':'Bias OFF'}</button><b data-testid="time">{time.toFixed(1)} s</b></div><div className="time"><span>0 s</span><input data-testid="timeSlider" type="range" min="0" max={MAXT} value={time} onChange={e=>{setRun(false);tref.current=+e.target.value;setTime(+e.target.value)}}/><span>600 s</span></div><canvas ref={main}/></section>
 <section className="card"><h2>Controls</h2><div className="controls">{defs.map(d=><div className="ctrl"><label><span>{d[1]}</span><b>{(+c[d[0]]).toFixed(d[5]==='mm'||d[5]==='×'?2:d[5]==='ppm'||d[5]==='vol%'?1:0)} {d[5]}</b></label><input data-testid={d[0]} type="range" min={d[2]} max={d[3]} step={d[4]} value={c[d[0]]} onChange={e=>set(d[0],e.target.value)}/></div>)}</div></section>
 <div className="cases">{card('Case A · dense clean AlN',a,'#39d98a')}{card('Case B · weak grain boundaries',b,'#ffb85c')}</div>
 <section className="card"><div className="plothead"><h2>Scientific curves</h2><select data-testid="plot" value={plot} onChange={e=>setPlot(e.target.value)}><option value="iv">Leakage I–V</option><option value="rho">Resistivity–temperature</option><option value="risk">Breakdown risk–time</option><option value="decay">Residual voltage decay</option></select></div><canvas ref={graph}/></section>
 <section className="card"><h2>Equations and limits</h2><div className="eq"><div><b style={{color:'#39d98a'}}>Physics-based</b><p className="mono">E=V/d</p><p className="mono">ρ(T)=ρ₂₅exp[(Eₐ/k)(1/T−1/T₂₅)]</p><p className="mono">R=ρd/A, I=V/R, P=VI</p></div><div><b style={{color:'#ffb85c'}}>Simplified / empirical</b><p className="mono">ρ(E)≈ρ(T)exp(−α√E)</p><p className="mono">D_F=1−exp(−k·pressure·rate·time)</p><p className="mono">Pᵦ=1−exp[−(E/E₀)ᵐ(t/t₀)ᵖ]</p></div></div><p className="sub"><b>Visual meaning:</b> cyan = electrons moving opposite E; orange = Na⁺ moving with E; green = fluorine radicals; purple = traps/secondary phase; red = local Joule heating. Numerical values are illustrative and are not NGK/Lam production limits.</p></section>
 </main>}
ReactDOM.createRoot(document.getElementById('root')).render(<CeramicElectricalReliabilitySimulator/>);
